sudo: false
language: erlang
otp_release:
  - 19.2
  - 18.2
  - 17.5
  - R16B02
  - R15B03
script:
  - make
  - make test-original
  - make test
  - git add -A ebin/*.S
  - git --no-pager diff
  - git --no-pager diff --cached
matrix:
  fast_finish: true
  allow_failures:
    - otp_release: 19.2
    - otp_release: 18.2
    - otp_release: 17.5
    - otp_release: R16B02
    - otp_release: R15B03
