sudo: false
language: erlang
otp_release:
  - 19.2
  - 18.2
  - 17.5
  - R16B02
  - R15B03
script:
  - make
  - make test
  - git add -A ebin/*.S
  - git --no-pager diff
  - git --no-pager diff --cached
